# Generated by Django 3.2.4 on 2023-04-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(max_length=50)),
                ('col2', models.CharField(max_length=50)),
                ('col3', models.CharField(max_length=50)),
            ],
        ),
    ]
